language: php

php:
  - 7.0
  - 5.6

notifications:
  slack: nukacode:HyFrc2QLi5PC5fPxadm07O5v

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --whitelist ./tests --coverage-clover ./coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml
